### ISSUE TITLE
Multiple Markdown editors in same component

### ISSUE THREAD

**Issue by Aman725** [jrm2k6/react-markdown-editor#26]
When we try to add multiple Markdown editors in same component, the MarkdownEditorMenu replicates actions in all the editors.

**Comment by jrm2k6** [comment]
Oh, I haven't planned for that. I can try to come up with a solution today or tomorrow, would it be fine with you? What are you using it for?

**Comment by jrm2k6** [comment]
Still haven't looked into it. Hopefully this weekend!

**Comment by jrm2k6** [comment]
Working on it @Aman725

**Comment by AnthonyMarshallBarfoot** [comment]
@jrm2k6  Was there any headway on this? I'm having the same issue.   If not,  I could have a stab at it and submit a PR

**Comment by jrm2k6** [comment]
Feel free to try it yes, I haven't really done anything on that issue.
