### ISSUE TITLE
Dynamic initialContent

### ISSUE THREAD

**Issue by Aman725** [jrm2k6/react-markdown-editor#27]
initialContent takes value only once on initial render. if the initial content changes on render it still shows the previous initial content

**Comment by jrm2k6** [comment]
Will make sure I double check. Thanks for opening the issue!

**Comment by jrm2k6** [comment]
We set an attribute content on the state of the root component, that we initially fetch from the props. So if you pass a new initialContent it won't replace the current content.
So if you unmount and remount the editor by specifying a new initial content it should work.
What is your use-case exactly?
