### ISSUE TITLE
Compatibility with React 0.15

### ISSUE THREAD

**Issue by devang-kredx** [jrm2k6/react-markdown-editor#28]
The library is not compatible with React 15 and above, so we are not able to use it in our project.

**Comment by jrm2k6** [comment]
What error do you see? I just started a new branch to check the compatibility and it seems to be working on my side.

**Comment by devang-kredx** [comment]
I see the following-
````
├── graceful-fs@4.1.3 
├── object-keys@1.0.9 
├── UNMET PEER DEPENDENCY react@15.0.1
├── UNMET PEER DEPENDENCY react-dom@15.0.1
└── react-markdown-editor@0.3.2  extraneous

````

**Comment by jrm2k6** [comment]
You can give a try to the react-15 branch, it should work just fine.
I will release really soon after running some more tests
