### ISSUE TITLE
Applying any of the markdowns doesn't trigger the change listener

### ISSUE THREAD

**Issue by stonecold123** [jrm2k6/react-markdown-editor#30]
When I apply any of the markdowns from the UI, it never triggers the change listener unless I type something after.  Is it possible to trigger the change once applying the markdowns because some people may apply markdowns only after finishing the text. 

```
class TextEditor extends React.Component{
     constructor(props){
          super(props)
          this.state = {comment:false}
     }
     render(){
            <MarkdownEditor onContentChange={this.onContentChange.bind(this)} initialContent="Test" iconsSet="font-awesome"/>
    }
    onContentChange(e){
        console.log(e)
        this.setState({comment:e})
    }
}
```

I wonder if this is a good idea to add  **this.props.onContentChange(_updatedContent);** in the updateText function in `MarkdownEditor.js`:

```
  updateText: function(text, selection, actionType) {
    var token = this.generateMarkdownToken(actionType);
    var beforeSelectionContent = text.slice(0, selection.selectionStart);
    var afterSelectionContent = text.slice(selection.selectionEnd, text.length);
    var updatedText = token.applyTokenTo(selection.selectedText);
    var _updatedContent = beforeSelectionContent + updatedText + afterSelectionContent;
    PublicMarkdownEditorActions.updateText(MarkdownUtils.toMarkdown(_updatedContent));
    this.setState({content: _updatedContent});
    this.props.onContentChange(_updatedContent); <<<
  },
```

**Comment by jrm2k6** [comment]
Hey, thanks for opening an issue.
The onChange event is triggered only on typing yes. You want to be notified when someone clicks on any of the buttons in the top menu?

I am not available today but I can work on it this week, would that be ok?

**Comment by stonecold123** [comment]
Thank you. I just made a pull request

**Comment by jrm2k6** [comment]
@stonecold123 Just pinging to see if you could add some unit tests for your change?
