### ISSUE TITLE
initialContent only access string with " "

### ISSUE THREAD

**Issue by wardenger** [jrm2k6/react-markdown-editor#32]
```
<MarkdownEditor
    initialContent= {this.state.article.body}          			
	iconsSet='font-awesome'
	onContentChange={this._onContentChange} />
<p>{this.state.article.body}</p>   //this can show normal
```

I need update article, so I need the initialContent have content after react render the pages

<p>{this.state.article.body}</p>   can show normal
while initialContent= {this.state.article.body} show nothing
it seems like the initialContent can only access "some string"

I don't know how to solve the problem......

**Comment by jrm2k6** [comment]
You mean, the value you pass a initialContent is not render at all, bit you
are able to print the content of the body in a console.log?

**Comment by wardenger** [comment]
```
{this.state.article.body ? <MarkdownEditor
          			initialContent= {this.state.article.body}          			
				        iconsSet='font-awesome'
				        onContentChange={this._onContentChange} /> : null
				      }
```

I got a friend helped change the code to this , and it run good

Thank you very much~
