### ISSUE TITLE
I want to use this

### ISSUE THREAD

**Issue by nomad5000** [jrm2k6/react-markdown-editor#33]
Hi I want to use this editor.

The first issue I have is that the fonts do not work on my install.

Maybe I could get svgs to deliver the icons. This would reduce the dependency on font awsome

What do you think?

Do you want me to dig into the code and do that change?

**Comment by jrm2k6** [comment]
Are you importing the right js file for font-awesome in the html markup mounting your react component?

**Comment by nomad5000** [comment]
I got it to work easily with the sample project.

When I wanted to use the editor in my project it did not work.

I'll have a look later and now that I know the project a bit better I'll
try to fix it.

Am Donnerstag, 3. November 2016 schrieb Jeremy Dagorn :
