### ISSUE TITLE
Saves content selected when clicking other button

### ISSUE THREAD

**Issue by nomad5000** [jrm2k6/react-markdown-editor#37]
Reproduce:

When selecting text then creating a list:

`+ test`

After clicking on list button then clikc on bold button

result

test will be printed with bold markup

**Comment by jrm2k6** [comment]
Hi,

What would you expect? List and bold?

**Comment by nomad5000** [comment]
Hi,

No I'm working on a fix and will send a PR tomorrow.

Am Donnerstag, 3. November 2016 schrieb Jeremy Dagorn :

**Comment by nomad5000** [comment]
duplicate #35

**Comment by nomad5000** [comment]
duplicate #35

**Comment by nomad5000** [comment]
duplicate #35

**Comment by nomad5000** [comment]
duplicate #35
