### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [jrm2k6/react-markdown-editor#4]
Would like to add to react.rocks...thanks.

**Comment by jrm2k6** [comment]
Sure. Will setup a small heroku app tonight! Is it OK with you?

**Comment by winkler1** [comment]
Sure - actually, Github Pages is probably better unless you need a backend... Heroku free apps often have that 5-10 second spinup time.

**Comment by jrm2k6** [comment]
I didn't have a lot of time to make it pretty. And I actually discovered some new features I want to add, but here it is http://jrm2k6.github.io/react-markdown-editor/

**Comment by winkler1** [comment]
Looking good - are all the buttons implemented? Seems like only Bold/Italic are working.

**Comment by jrm2k6** [comment]
It should yes.
Which browser are you using?
You need to make sure you select some text before clicking the button, as it is not remembering your selection after clicking on the textarea, or typing again.

**Comment by winkler1** [comment]
Chrome...I see what you're saying now. Think it's more a user expectations issue, since the buttons were enabled, I mindlessly clicked them :). Not sure how most editors handle this. Incidentally, would be good to support common kbd shortcuts? Cmd-B, Cmd-I, perhaps Cmd-L to link..

**Comment by jrm2k6** [comment]
You can open an issue for that. That is why I re-specified beta-ish! :DYes, it should be easy to disable the buttons until you have a selection, that's a perfectly valid expectation.

**Comment by jrm2k6** [comment]
@winkler1 I pushed a new version where buttons are disabled when there is no selection.
It will disable then again when you type, or click on the textarea.
I haven't fixed yet the issue where selection using keyboard shortcuts doesn't enable the button but I plan on doing it soon.

Wdyt?
