### ISSUE TITLE
onContentChange not triggered when formatting buttons clicked

### ISSUE THREAD

**Issue by d-winter** [jrm2k6/react-markdown-editor#42]
Hi,
I saw the onContentChange callback is not triggered when click on on of the formatting buttons.
e.g: When I select some text in the markdown editor and click "Header", the editor includes the formatting chars. 
I think this should trigger the onContentChange callback?

**Comment by jrm2k6** [comment]
Will check. Thanks for opening the issue!

**Comment by mlukaszczyk** [comment]
Hey @jrm2k6,

did you have a chance to take a look on this issue? Would be great!

Thanks,

Michael

**Comment by jrm2k6** [comment]
Not yet sadly. Hopefully tonight! Sorry for that.

**Comment by jrm2k6** [comment]
Hey @mlukaszczyk and @d-winter Just tried on the latest version to be released, and that issue is fixed.

**Comment by mlukaszczyk** [comment]
Thanks a lot!

**Comment by jrm2k6** [comment]
It has been released, let me know if it works. npm install react-markdown-editor@0.5.0. I should be back in a few hours. If anything is broken, just revert back to 0.4.0
