### ISSUE TITLE
Unexpected token (49:19)

### ISSUE THREAD

**Issue by Inumedia** [jrm2k6/react-markdown-editor#51]
Hi,

When trying to use this with the latest `create-react-app`, I get the error `Unexpected token (49:19)`:
![image](https://user-images.githubusercontent.com/856822/28753171-75ebbffe-74f5-11e7-979c-2badac21115c.png)

Looks like the issue is due to the elements not being wrapped in parenthesis.

**Comment by jrm2k6** [comment]
Looks like it is related to webpack. I will give it a shot against the
latest create react app.

**Comment by Inumedia** [comment]
:+1:

**Comment by Jack-Works** [comment]
Same problem

**Comment by jrm2k6** [comment]
@Inumedia @Jack-Works Checking. Probably something related to my webpack config, I am surprised to see that it tries to load from the src folder, and not the dist (where JSX is transformed to the JS equivalent).

**Comment by Jack-Works** [comment]
@jrm2k6 Maybe it is the problem of "module": index.js in package.json, this file point to src instead of dist

**Comment by jrm2k6** [comment]
Yep! Removed that line actually. Can you give a shot to 0.6.1-rc.1?

**Comment by Jack-Works** [comment]
I didn't see 0.6.1-rc.1 on any branch...but I guess it will work
By the way, after I gave up #52 , I spent few hours to write a simple markdown editor, and it is good enough for me at present. Maybe I can try this project in furture.
I have great hope for adding types definition to this project. Thanks for your working

**Comment by jrm2k6** [comment]
@Jack-Works It is a beta tag so that might be why it doesn't appear in the releases tab.
0.6.1-rc.1 seems to be working for me. Can you pull down and confirm (and also check the package.json of the pulled-down module)?
Thanks!

Your PR for 52 was quite big, with a lot of changes. What was your end goal exactly?

**Comment by Jack-Works** [comment]
Nothing speical, the first is fix this problem, but i didn't get the right point, the second is add .d.ts file for my environment.

**Comment by jrm2k6** [comment]
Not sure I want to definition file in this repo. Let me know if the beta
works for you

**Comment by Jack-Works** [comment]
Alright, I will try it later. (It's 1am here). Adding a definition file is
painless, you can do it without modify any file than package.json

**Comment by Jack-Works** [comment]
@jrm2k6 Yes, it works for me, no compile error

**Comment by jrm2k6** [comment]
@Inumedia I think the new version should fix that issue. I will close the issue for now. Feel free to reopen if still not good.
