### ISSUE TITLE
[feature] github flavoured markdown

### ISSUE THREAD

**Issue by u007** [jrm2k6/react-markdown-editor#54]
hi,

any plans to implement this?

https://github.github.com/gfm/

https://github.com/vincent-p/react-marked-markdown

thank you

**Comment by u007** [comment]
yes a lot more features
especially table

**Comment by jrm2k6** [comment]
I have no plan to implement this no. The markdown to html rendering is done using the markdown package so if maybe gfm has a library we can just use that could be possible.
As usual, PRs are more than welcome.

**Comment by jrm2k6** [comment]
Closing this as is it not in my immediate plans to do it.
